id = "kickassembler"
name = "Kick Assembler Support"
version = "0.2.0"
schema_version = 1
authors = ["Chris Page <chris@designchaos.net>"]
description = "Language support for Kick Assembler"
repository = "https://github.com/chrx/zed-kickassembler"

[grammars.kickassembler]
repository = "https://github.com/chrx/tree-sitter-kickassembler"
rev="cab8100f901048e2b60667c5bca3be2e5e8b4d27"
