id = "kickassembler"
name = "Kick Assembler Support"
version = "0.2.1"
schema_version = 1
authors = ["Chris Page <chris@designchaos.net>"]
description = "Language support for Kick Assembler"
repository = "https://github.com/chrx/zed-kickassembler"

[grammars.kickassembler]
repository = "https://github.com/chrx/tree-sitter-kickassembler"
rev="08eed81a4d882e24b50164bb9632e5f6ab8b69a8"
