id = "kickassembler"
name = "Kick Assembler Support"
version = "0.2.0"
schema_version = 1
authors = ["Chris Page <chris@designchaos.net>"]
description = "Language support for Kick Assembler"
repository = "https://github.com/chrx/zed-kickassembler"

[grammars.kickassembler]
repository = "https://github.com/chrx/tree-sitter-kickassembler"
